---
title: "NEO BMI-Metabolite Circos Plot"
author: "David Hughes"
date: "1/25/2022"
output: 
  pdf_document:
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)

source("LOAD.R")

```


## Load point estimates

```{r}
w = which(par_data[,1] == "results_dir")
resultsdir = par_data[w,2]

f = paste0(resultsdir, "obs_tsls_estimates_Dec12_2022.Rdata")
load( f)

## long format data
f = paste0(resultsdir, "obs_tsls_estimates_long_Dec12_2022.Rdata")
load( file = f)

```


```{r}
## install epiviz
# devtools::install_github("mattlee821/EpiViz/R_package")

## load package
library(EpiViz)
library(RColorBrewer)

source("functions/circos_plot.R")
```



## Define a new feature annotation data frame

```{r}
## metabolite ids
# mids = gsub("_f","",traits); mids = gsub("_p","",mids); mids = gsub("_r","",mids)
fanno = study_data$feature_anno
m = match(traits, fanno$new_id)
## define new feature annotation
new_fanno = fanno[m, ]
## edit new data frame
##### update metabolite names
new_fanno$metabolite = rep(metids, 3)
##### update traits names
new_fanno$new_id = traits
##### update dietary state
w = which( is.na( new_fanno$dietary_state ) ); new_fanno$dietary_state[w] = "response"
##### add missing annotation
w = which(is.na(new_fanno$raw.label))
m = match( new_fanno$metabolite[w], new_fanno$metabolite )
new_fanno[w,5:10] = new_fanno[m,5:10] 

## redefine feature annotation file
study_data$feature_anno = new_fanno

rownames(study_data$feature_anno) = 1:nrow(study_data$feature_anno)
```


# Observational Circos Plot

```{r}
temp = obs_tsls_est$wNEO
#######
f = grep("_f", temp$outcome)
fasting = temp[f, c("outcome","Obs_beta","Obs_se","Obs_P")]
fasting$lower_CI = fasting$Obs_beta - fasting$Obs_se
fasting$upper_CI = fasting$Obs_beta + fasting$Obs_se
m = match(fasting$outcome, study_data$feature_anno$new_id)
fasting = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], fasting)

#######

p = grep("_p", temp$outcome)
postprandial = temp[p, c("outcome","Obs_beta","Obs_se","Obs_P")]
postprandial$lower_CI = postprandial$Obs_beta - postprandial$Obs_se
postprandial$upper_CI = postprandial$Obs_beta + postprandial$Obs_se
m = match(postprandial$outcome, study_data$feature_anno$new_id)
postprandial = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], postprandial)


#######
r = grep("_r", temp$outcome)
response = temp[r, c("outcome","Obs_beta","Obs_se","Obs_P")]
response$lower_CI = response$Obs_beta - response$Obs_se
response$upper_CI = response$Obs_beta + response$Obs_se
m = match(response$outcome, study_data$feature_anno$new_id)
response = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], response)

#######
cir_data = list(response = response, postprandial = postprandial, fasting = fasting)
### drop unwanted levels
for(i in 1:3){
  cir_data[[i]]$outcome = droplevels( as.factor(cir_data[[i]]$outcome) )
  cir_data[[i]]$class = droplevels( as.factor(cir_data[[i]]$class) )
  cir_data[[i]]$subclass = droplevels( as.factor(cir_data[[i]]$subclass) )
  cir_data[[i]]$dietary_state = droplevels( as.factor(cir_data[[i]]$dietary_state) )
}

```



```{r}
######################################
## We have to add a random new column
## of data to avoid a length data
## length factor error. Do not know
##  why. It just works !
######################################
for(i in 1:length(cir_data)){
  cir_data[[i]]$b <- rnorm( nrow(cir_data[[i]]), mean = 0.1, sd = 1)
}

```

```{r}
# ################################
# ## Need to make the response
# ## data frame the same size as the others
# ################################
# temp = cir_data$response
# m = match(cir_data$fasting$metabolite, temp$metabolite)
# temp = temp[m,]
# temp[is.na(temp)] = 0
# temp$metabolite = cir_data$fasting$metabolite
# temp$class = cir_data$fasting$class
# temp$subclass = cir_data$fasting$subclass
# rownames(temp) = 1:nrow(temp)
# ###
# cir_data$response = temp
# ###
# rownames(cir_data$postprandial) = 1:nrow(cir_data$postprandial)
```


```{r, fig.width = 10, fig.height = 10}
################################
## Test Plot with 1 Track
################################
pcol = brewer.pal(3, "Set1")
discrete_palette = c(pcol[1], pcol[2], pcol[3])
####
w = which(par_data[,1] == "results_dir")
f = paste0( par_data[w,2] , "figures/wNEO_Obs_circos.pdf")
pdf(f, width = 12, height = 12, useDingbats=FALSE )

circos_plot(track_number = 3, # how many tracks do you want to plot
            track1_data = cir_data$response, # what is the dataframe for your first track
            track2_data = cir_data$postprandial,
            track3_data = cir_data$fasting,
            track1_type = "points", # how do you want to plot your first track
            track2_type = "points",
            track3_type = "points",
            label_column = 1, # whats is the column of your labels
            section_column = 4, # what is the column of your sections
            estimate_column = 6, # what is the column of your estimate (beta, OR etc.)
            lower_ci = 9, # what is the column of your lower confidence interval
            upper_ci = 10,
            pvalue_column = 8,
            pvalue_adjustment = 0.05/43,
            circle_size = 10,
            equal_axis = TRUE ) # what is the column of your upper confidence interval

dev.off()

```

# MR Circos Plot

```{r}
temp = obs_tsls_est$wNEO
#######
f = grep("_f", temp$outcome)
fasting = temp[f, c("outcome","MR_beta","MR_se","MR_P")]
fasting$lower_CI = fasting$MR_beta - fasting$MR_se
fasting$upper_CI = fasting$MR_beta + fasting$MR_se
m = match(fasting$outcome, study_data$feature_anno$new_id)
fasting = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], fasting)

#######

p = grep("_p", temp$outcome)
postprandial = temp[p, c("outcome","MR_beta","MR_se","MR_P")]
postprandial$lower_CI = postprandial$MR_beta - postprandial$MR_se
postprandial$upper_CI = postprandial$MR_beta + postprandial$MR_se
m = match(postprandial$outcome, study_data$feature_anno$new_id)
postprandial = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], postprandial)


#######
r = grep("_r", temp$outcome)
response = temp[r, c("outcome","MR_beta","MR_se","MR_P")]
response$lower_CI = response$MR_beta - response$MR_se
response$upper_CI = response$MR_beta + response$MR_se
m = match(response$outcome, study_data$feature_anno$new_id)
response = cbind( study_data$feature_anno[m, c("metabolite","dietary_state", "class", "subclass")], response)

#######
cir_data = list(response = response, postprandial = postprandial, fasting = fasting)
### drop unwanted levels
for(i in 1:3){
  cir_data[[i]]$outcome = droplevels( as.factor(cir_data[[i]]$outcome) )
  cir_data[[i]]$class = droplevels( as.factor(cir_data[[i]]$class) )
  cir_data[[i]]$subclass = droplevels( as.factor(cir_data[[i]]$subclass) )
  cir_data[[i]]$dietary_state = droplevels( as.factor(cir_data[[i]]$dietary_state) )
}

```



```{r}
######################################
## We have to add a random new column
## of data to avoid a length data
## length factor error. Do not know
##  why. It just works !
######################################
for(i in 1:length(cir_data)){
  cir_data[[i]]$b <- rnorm( nrow(cir_data[[i]]), mean = 0.1, sd = 1)
}

```

```{r}
# ################################
# ## Need to make the response
# ## data frame the same size as the others
# ################################
# temp = cir_data$response
# m = match(cir_data$fasting$metabolite, temp$metabolite)
# temp = temp[m,]
# temp[is.na(temp)] = 0
# temp$metabolite = cir_data$fasting$metabolite
# temp$class = cir_data$fasting$class
# temp$subclass = cir_data$fasting$subclass
# rownames(temp) = 1:nrow(temp)
# ###
# cir_data$response = temp
# ###
# rownames(cir_data$postprandial) = 1:nrow(cir_data$postprandial)
```


```{r, fig.width = 10, fig.height = 10}
################################
## Test Plot with 1 Track
################################
pcol = brewer.pal(3, "Set1")
discrete_palette = c(pcol[1], pcol[2], pcol[3])
####
w = which(par_data[,1] == "results_dir")
f = paste0( par_data[w,2] , "figures/wNEO_MR_circos.pdf")
pdf(f, width = 12, height = 12, useDingbats=FALSE )

circos_plot(track_number = 3, # how many tracks do you want to plot
            track1_data = cir_data$response, # what is the dataframe for your first track
            track2_data = cir_data$postprandial,
            track3_data = cir_data$fasting,
            track1_type = "points", # how do you want to plot your first track
            track2_type = "points",
            track3_type = "points",
            label_column = 1, # whats is the column of your labels
            section_column = 4, # what is the column of your sections
            estimate_column = 6, # what is the column of your estimate (beta, OR etc.)
            lower_ci = 9, # what is the column of your lower confidence interval
            upper_ci = 10,
            pvalue_column = 8,
            pvalue_adjustment = 0.05/43,
            circle_size = 10,
            equal_axis = TRUE ) # what is the column of your upper confidence interval

dev.off()

```
